server:
  port: 8080

spring:
  datasource:
    name: myBlog
    url: jdbc:mysql://localhost:3306/my_blog_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis-plus:
  type-aliases-package: com.site.blog.entity
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: "tb_"

logging:
  level.com.site.blog: debug

upload:
  uploadAuthorImg: "D:/tmp/myblog/authorImg/"
  fileUploadDic: "D:/tmp/myblog/upload/"
  sqlAuthorImg: "/authorImg/"
  fileSqlDic: "/upload/"

